application: websockets
version: 1
runtime: php
api_version: 1

skip_files:
  - ^(.*/)?.*/bin/.*$
  - ^(.*/)?.*/obj/.*$
  - ^(.*/)?.*/Properties/.*$ 
  - ^(.*/)?.*\.csproj
  - ^(.*/)?.*\.csproj.user
  - ^(.*/)?.*\.config

handlers:
- url: /css 
  static_dir: css
  
- url: /img 
  static_dir: img

- url: /js 
  static_dir: js
  
- url: /.*
  script: index.html

  

  
